### ISSUE TITLE
Requirements.txt is empty

### ISSUE THREAD

**Issue by felipedbene** [aws-samples/aws-control-tower-securityhub-enabler#20]
Requirements.txt is empty, package.sh fails because of it and consequenty the lambda.

**Comment by silicon-jc** [comment]
Since we no longer have any third party imports, I have removed the need to package the zip file, and included it in the repo.  The package.sh and package.ps1 scripts should no longer be bothered by the empty requirements.txt, if you make changes to the .py and want to create your own zip file.

Pull the latest version and you should be good.

Thanks
